# config used for Snakemake 


remote: true

gcloud:
    bucket: "lvt-schiphol-assignment-snakemake"
    credentials: "keys/bucket-access.json"


mlflow:
    experiment: "schiphol-snakemake"
    tracking_uri: "lvt-schiphol-assignment-snakemake/mlruns"

raw_files:
    - "flights.csv"
    - "airports.csv"


trelliscope:
    path: "trelliscope"

train_test:
    test_size:
        - 0.2
    strategy:
        - sample
        - timeseries


models:
  - baseline_average
  # - catboost_simple