# config used for Snakemake 


remote: false

gcloud:
    bucket: lvt-schiphol-assignment-snakemake
    credentials: "keys/bucket-access.json"


mlflow:
    credentials: "keys/mlflow-access.json"
    server: "http://35.204.210.2:5000"
    pipeline_experiment: "sklearn_pipeline__snakemake"

raw_files:
    - "flights.csv"
    - "airports.csv"


train_test:
    test_size:
        - 0.2
    strategy:
        - sample
        - timeseries